"use client";

import "./globals.css";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Vasyl Miskiv",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider enableSystem={true} attribute="class">
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
